version: 5.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: 
  - Debug
  - Release
platform: Any CPU
before_build:
  - cmd: nuget restore LiteDB.sln
build:
  project: LiteDB.sln
  verbosity: minimal
for:
-
  matrix:
    only:
      - configuration: Release
  artifacts:
    - path: LiteDB\bin\Release\net45\LiteDB.dll
  deploy:
  - provider: Webhook
    url: https://app.signpath.io/API/v1/b97db90c-7c03-416b-9003-8ed45742da5f/Integrations/AppVeyor?ProjectKey=mbdavid-LiteDB&SigningPolicyKey=test-signing
    authorization:
      secure: 3ty5yk+UWhjVAtwwPm8StZjmg1H6WtcCvQ7+KCiP0lQQuTDy/PvNCXbGvoKZbp8rxce4YSpAxzKuYuKucgXqKg==