version: 5.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Debug
platform: Any CPU
before_build:
- cmd: nuget restore LiteDB.sln
build:
  project: LiteDB.sln
  verbosity: minimal