version: 5.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: 
  - Debug
  - Release
platform: Any CPU
before_build:
  - cmd: nuget restore LiteDB.sln
build:
  project: LiteDB.sln
  verbosity: minimal
for:
-
  matrix:
    only:
      - configuration: Release
  after_build:
    - ps: Compress-Archive -Path "LiteDB\bin\Release\net45\LiteDB.dll", "LiteDB.Shell\bin\Release\netcoreapp2.1\LiteDB.Shell.dll" -CompressionLevel "Optimal" -DestinationPath "release-${env:APPVEYOR_BUILD_VERSION}.zip"
  artifacts:
    - path: release-*.zip
  deploy:
  - provider: Webhook
    url: https://app.signpath.io/API/v1/b97db90c-7c03-416b-9003-8ed45742da5f/Integrations/AppVeyor?ProjectKey=mbdavid-LiteDB&SigningPolicyKey=test-signing
    authorization:
      secure: 5Xj6LCgkuuxTKbNrjQHcGeijmtDAK4fCOwdyD5KOQed2T5tz9rdk5jmw4asn9V6mOi9y0Xi335lK8Ec7spTomA==